<?php

namespace Database\Seeders;

use App\Models\Animal;
use Illuminate\Database\Seeder;

class ArcticAnimalSeeder extends Seeder
{
    public function run(): void
    {
        $animals = [
            [
                'name'                => 'Polar Bear',
                'species'             => 'Polar Bear',
                'scientific_name'     => 'Ursus maritimus',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Carnivore',
                'lifespan'            => '20-30 years',
                'conservation_status' => 'Vulnerable',
                'description'         => 'The polar bear is the world\'s largest land carnivore and the apex predator of the Arctic. Its thick fur and a 10 cm layer of insulating fat allow it to survive in temperatures as low as -50°C. Polar bears are classified as marine mammals because they spend most of their lives on sea ice.',
                'image'               => '/images/animals/polar-bear-1.jpg',
                'gallery'             => json_encode(['/images/animals/polar-bear-1.jpg', '/images/animals/polar-bear-2.jpg']),
                'fun_facts'           => json_encode([
                    'Polar bear fur is actually transparent, not white — it reflects light.',
                    'They can swim for days, covering up to 100 km without stopping.',
                    'A polar bear\'s liver contains enough vitamin A to be lethal to humans.',
                ]),
                'weight' => '700 kg', 'height' => '1.6 m', 'speed' => '40 km/h',
            ],
            [
                'name'                => 'Arctic Fox',
                'species'             => 'Arctic Fox',
                'scientific_name'     => 'Vulpes lagopus',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Omnivore',
                'lifespan'            => '3-6 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The Arctic fox is a master of survival in the harshest conditions on Earth. Its thick, multilayered fur coat changes from white in winter to brown in summer for camouflage. It can withstand temperatures as low as -70°C — the coldest temperature tolerance of any mammal.',
                'image'               => '/images/animals/arctic-fox-1.jpg',
                'gallery'             => json_encode(['/images/animals/arctic-fox-1.jpg', '/images/animals/arctic-fox-2.jpg']),
                'fun_facts'           => json_encode([
                    'Arctic foxes can tolerate -70°C — colder than any other mammal.',
                    'Their fluffy tail acts as a blanket to keep warm while sleeping.',
                    'They follow polar bears to scavenge leftover seal carcasses.',
                ]),
                'weight' => '3.5 kg', 'height' => '0.3 m', 'speed' => '50 km/h',
            ],
            [
                'name'                => 'Snowy Owl',
                'species'             => 'Snowy Owl',
                'scientific_name'     => 'Bubo scandiacus',
                'category'            => 'Bird',
                'habitat_id'          => 4,
                'diet'                => 'Carnivore',
                'lifespan'            => '10-25 years',
                'conservation_status' => 'Vulnerable',
                'description'         => 'The snowy owl is one of the largest owls and a true icon of the Arctic tundra. Unlike most owls, snowy owls are diurnal — they hunt during the day. Their striking white plumage provides perfect camouflage in the snow-covered landscape.',
                'image'               => '/images/animals/snowy-owl-1.jpg',
                'gallery'             => json_encode(['/images/animals/snowy-owl-1.jpg', '/images/animals/snowy-owl-2.jpg']),
                'fun_facts'           => json_encode([
                    'Snowy owls hunt during the day, unlike most owl species.',
                    'A male snowy owl turns almost completely white with age.',
                    'They can eat up to 1,600 lemmings per year.',
                ]),
                'weight' => '2.3 kg', 'height' => '0.65 m', 'speed' => '80 km/h',
            ],
            [
                'name'                => 'Narwhal',
                'species'             => 'Narwhal',
                'scientific_name'     => 'Monodon monoceros',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Carnivore',
                'lifespan'            => '50-80 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The narwhal is one of the most extraordinary animals on Earth, nicknamed the "unicorn of the sea" for its long spiral tusk. The tusk is actually a modified canine tooth that can grow up to 3 metres in males and contains millions of sensory nerve endings, acting as a sophisticated environmental sensor.',
                'image'               => '/images/animals/narwhal-1.jpg',
                'gallery'             => json_encode(['/images/animals/narwhal-1.jpg', '/images/animals/narwhal-2.jpg']),
                'fun_facts'           => json_encode([
                    'The narwhal\'s tusk can grow up to 3 metres long.',
                    'Their tusk has 10 million nerve endings and can sense water temperature and salinity.',
                    'They can dive to 1,500 metres — deeper than most whales.',
                ]),
                'weight' => '1,600 kg', 'height' => '5 m (length)', 'speed' => '25 km/h',
            ],
            [
                'name'                => 'Walrus',
                'species'             => 'Walrus',
                'scientific_name'     => 'Odobenus rosmarus',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Carnivore',
                'lifespan'            => '40 years',
                'conservation_status' => 'Vulnerable',
                'description'         => 'The walrus is one of the most recognisable Arctic animals, famous for its long ivory tusks and whiskered face. Both males and females grow tusks, which they use to haul themselves out of the water, establish dominance, and even break breathing holes through ice from below.',
                'image'               => '/images/animals/walrus-1.jpg',
                'gallery'             => json_encode(['/images/animals/walrus-1.jpg', '/images/animals/walrus-2.jpg']),
                'fun_facts'           => json_encode([
                    'A walrus can use its tusks to pull itself out of the water.',
                    'Their 15 cm thick skin protects them from cold Arctic waters.',
                    'Walruses can slow their heartbeat to survive near-freezing water.',
                ]),
                'weight' => '1,700 kg', 'height' => '3.6 m (length)', 'speed' => '35 km/h',
            ],
            [
                'name'                => 'Arctic Wolf',
                'species'             => 'Arctic Wolf',
                'scientific_name'     => 'Canis lupus arctos',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Carnivore',
                'lifespan'            => '7-10 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The Arctic wolf is a subspecies of the gray wolf uniquely adapted to the brutal conditions of the High Arctic. Their white coat provides perfect camouflage on snow and ice. Unlike other wolf populations, Arctic wolves have had little contact with humans and show surprisingly low fear of people.',
                'image'               => '/images/animals/arctic-wolf-1.jpg',
                'gallery'             => json_encode(['/images/animals/arctic-wolf-1.jpg', '/images/animals/arctic-wolf-2.jpg']),
                'fun_facts'           => json_encode([
                    'Arctic wolves can go months without food during polar night.',
                    'They are the only subspecies of wolf not threatened by humans.',
                    'Their paws have special adaptations to grip slippery ice.',
                ]),
                'weight' => '45 kg', 'height' => '0.8 m', 'speed' => '70 km/h',
            ],
            [
                'name'                => 'Beluga Whale',
                'species'             => 'Beluga Whale',
                'scientific_name'     => 'Delphinapterus leucas',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Carnivore',
                'lifespan'            => '35-50 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The beluga whale, known as the "canary of the sea" for its rich vocal repertoire, is one of the most social and expressive whales. Their striking white colour — unique among whales — develops with age. Remarkably, belugas can turn their heads in any direction, unlike most whales whose necks are fused.',
                'image'               => '/images/animals/beluga-whale-1.jpg',
                'gallery'             => json_encode(['/images/animals/beluga-whale-1.jpg', '/images/animals/beluga-whale-2.jpg']),
                'fun_facts'           => json_encode([
                    'Belugas are called the "canary of the sea" for their wide range of sounds.',
                    'They are born grey and turn white as they mature.',
                    'Belugas can turn their head in any direction — most whales cannot.',
                ]),
                'weight' => '1,500 kg', 'height' => '5 m (length)', 'speed' => '22 km/h',
            ],
            [
                'name'                => 'Reindeer',
                'species'             => 'Reindeer',
                'scientific_name'     => 'Rangifer tarandus',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Herbivore',
                'lifespan'            => '15-20 years',
                'conservation_status' => 'Vulnerable',
                'description'         => 'Reindeer — called caribou in North America — are the only deer species where both males and females grow antlers. They are remarkable long-distance travellers, undertaking the longest land migration of any land animal, covering up to 5,000 km per year following seasonal food sources.',
                'image'               => '/images/animals/reindeer-1.jpg',
                'gallery'             => json_encode(['/images/animals/reindeer-1.jpg', '/images/animals/reindeer-2.jpg']),
                'fun_facts'           => json_encode([
                    'Reindeer can see ultraviolet light — useful for spotting wolves in the snow.',
                    'Both males and females grow antlers — unique among deer.',
                    'Their nose warms Arctic air before it reaches their lungs.',
                ]),
                'weight' => '160 kg', 'height' => '1.2 m', 'speed' => '80 km/h',
            ],
            [
                'name'                => 'Musk Ox',
                'species'             => 'Musk Ox',
                'scientific_name'     => 'Ovibos moschatus',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Herbivore',
                'lifespan'            => '12-20 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The musk ox is a true Ice Age survivor that has barely changed in 700,000 years. Its thick, shaggy coat — with a fine undercoat called qiviut — is eight times warmer than sheep wool. When threatened by wolves or bears, musk oxen form a defensive circle with their horns facing outward.',
                'image'               => '/images/animals/musk-ox-1.jpg',
                'gallery'             => json_encode(['/images/animals/musk-ox-1.jpg', '/images/animals/musk-ox-2.jpg']),
                'fun_facts'           => json_encode([
                    'Their undercoat (qiviut) is 8 times warmer than sheep wool.',
                    'Musk oxen survived the last Ice Age when woolly mammoths did not.',
                    'They form a defensive circle facing outward to protect calves from predators.',
                ]),
                'weight' => '400 kg', 'height' => '1.5 m', 'speed' => '60 km/h',
            ],
            [
                'name'                => 'Arctic Hare',
                'species'             => 'Arctic Hare',
                'scientific_name'     => 'Lepus arcticus',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Herbivore',
                'lifespan'            => '3-5 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The Arctic hare is a large hare superbly adapted to life in the frozen north. It remains white year-round in the High Arctic where snow never fully melts. They can survive on woody plants, mosses, and even tree bark when buried under deep snow.',
                'image'               => '/images/animals/arctic-hare-1.jpg',
                'gallery'             => json_encode(['/images/animals/arctic-hare-1.jpg', '/images/animals/arctic-hare-2.jpg']),
                'fun_facts'           => json_encode([
                    'Arctic hares can run up to 60 km/h and leap 2 metres in a single bound.',
                    'They dig through snow with their strong claws to reach food.',
                    'Groups of hundreds huddle together for warmth in blizzards.',
                ]),
                'weight' => '5.5 kg', 'height' => '0.7 m (length)', 'speed' => '60 km/h',
            ],
            [
                'name'                => 'Atlantic Puffin',
                'species'             => 'Atlantic Puffin',
                'scientific_name'     => 'Fratercula arctica',
                'category'            => 'Bird',
                'habitat_id'          => 4,
                'diet'                => 'Carnivore',
                'lifespan'            => '20-25 years',
                'conservation_status' => 'Vulnerable',
                'description'         => 'The Atlantic puffin is a charismatic seabird nicknamed the "clown of the sea" for its colourful beak and waddling gait. Despite their awkward appearance on land, puffins are extraordinary athletes — they can flap their wings up to 400 times per minute and dive up to 60 metres underwater.',
                'image'               => '/images/animals/puffin-1.jpg',
                'gallery'             => json_encode(['/images/animals/puffin-1.jpg', '/images/animals/puffin-2.jpg']),
                'fun_facts'           => json_encode([
                    'Puffins can carry up to 62 fish in their beak at once.',
                    'They flap their wings 400 times per minute in flight.',
                    'Puffin couples return to the same burrow every year for life.',
                ]),
                'weight' => '0.5 kg', 'height' => '0.3 m', 'speed' => '88 km/h',
            ],
            [
                'name'                => 'Wolverine',
                'species'             => 'Wolverine',
                'scientific_name'     => 'Gulo gulo',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Omnivore',
                'lifespan'            => '5-13 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The wolverine is pound-for-pound one of the most ferocious and tenacious animals on Earth. This stocky mustelid can drive away bears and wolves from their kills and has been documented killing prey ten times its size. Its broad, snowshoe-like paws make it a supreme traveller across Arctic snowfields.',
                'image'               => '/images/animals/wolverine-1.jpg',
                'gallery'             => json_encode(['/images/animals/wolverine-1.jpg', '/images/animals/wolverine-2.jpg']),
                'fun_facts'           => json_encode([
                    'Wolverines have been documented driving grizzly bears away from kills.',
                    'They can travel 40 km a day through deep snow without tiring.',
                    'Their jaws are strong enough to crush frozen bones.',
                ]),
                'weight' => '18 kg', 'height' => '0.45 m', 'speed' => '30 km/h',
            ],
            [
                'name'                => 'Harp Seal',
                'species'             => 'Harp Seal',
                'scientific_name'     => 'Pagophilus groenlandicus',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Carnivore',
                'lifespan'            => '25-30 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The harp seal is named for the harp-shaped marking on the backs of adults. Famous for their irresistibly cute white pups, newborns are helpless and rely entirely on their mother\'s rich milk — which contains 45% fat — enabling them to triple their weight in just 12 days before being left to fend for themselves.',
                'image'               => '/images/animals/harp-seal-1.jpg',
                'gallery'             => json_encode(['/images/animals/harp-seal-1.jpg', '/images/animals/harp-seal-2.jpg']),
                'fun_facts'           => json_encode([
                    'Harp seal pups triple their weight in just 12 days.',
                    'Their mothers identify them by smell in crowded breeding colonies.',
                    'They can dive to 300 metres and hold their breath for 15 minutes.',
                ]),
                'weight' => '135 kg', 'height' => '1.7 m (length)', 'speed' => '30 km/h',
            ],
            [
                'name'                => 'Arctic Tern',
                'species'             => 'Arctic Tern',
                'scientific_name'     => 'Sterna paradisaea',
                'category'            => 'Bird',
                'habitat_id'          => 4,
                'diet'                => 'Carnivore',
                'lifespan'            => '20-30 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The Arctic tern holds the record for the longest migration of any animal on Earth. Each year it travels from the Arctic to Antarctica and back — a round trip of up to 80,000 km. Over its lifetime, a single Arctic tern may fly the equivalent of three trips to the Moon and back.',
                'image'               => '/images/animals/arctic-tern-1.jpg',
                'gallery'             => json_encode(['/images/animals/arctic-tern-1.jpg', '/images/animals/arctic-tern-2.jpg']),
                'fun_facts'           => json_encode([
                    'The Arctic tern has the longest migration of any animal — 80,000 km a year.',
                    'In a lifetime, one tern may fly the equivalent of three trips to the Moon.',
                    'They experience two summers per year — more sunlight than any other animal.',
                ]),
                'weight' => '0.11 kg', 'height' => '0.35 m', 'speed' => '40 km/h',
            ],
            [
                'name'                => 'Lemming',
                'species'             => 'Norway Lemming',
                'scientific_name'     => 'Lemmus lemmus',
                'category'            => 'Mammal',
                'habitat_id'          => 4,
                'diet'                => 'Herbivore',
                'lifespan'            => '1-3 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The Norway lemming is a small but fiercely aggressive rodent that forms the base of the Arctic food web. Its famous population explosions and mass migrations are critical to the ecosystem — feeding snowy owls, Arctic foxes, and other predators. The myth of lemmings jumping off cliffs is completely false.',
                'image'               => '/images/animals/lemming-1.jpg',
                'gallery'             => json_encode(['/images/animals/lemming-1.jpg', '/images/animals/lemming-2.jpg']),
                'fun_facts'           => json_encode([
                    'Lemmings are surprisingly aggressive — they will face down predators.',
                    'The myth of lemmings jumping off cliffs was faked in a 1958 Disney documentary.',
                    'Their populations cycle dramatically every 3-5 years, controlling the Arctic food web.',
                ]),
                'weight' => '0.11 kg', 'height' => '0.15 m (length)', 'speed' => '5 km/h',
            ],
        ];

        foreach ($animals as $animal) {
            Animal::create($animal);
        }
    }
}
