<?php

namespace Database\Seeders;

use App\Models\Animal;
use Illuminate\Database\Seeder;

class ForestAnimalSeeder extends Seeder
{
    public function run(): void
    {
        $animals = [
            [
                'name' => 'Red Fox', 'species' => 'Red Fox', 'scientific_name' => 'Vulpes vulpes',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Omnivore', 'lifespan' => '3-5 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The red fox is the largest of the true foxes and one of the most widely distributed carnivores in the world. Known for its cunning intelligence and beautiful russet coat, it thrives in forests across the Northern Hemisphere.',
                'image' => '/images/animals/red_fox_1.png',
                'gallery' => json_encode(['/images/animals/red_fox_1.png', '/images/animals/red_fox_2.png']),
                'fun_facts' => json_encode(['Foxes can hear a watch ticking 40 yards away!', 'They use Earth\'s magnetic field to hunt.', 'A fox\'s tail is called a "brush".']),
                'weight' => '6 kg', 'height' => '0.4 m', 'speed' => '50 km/h',
            ],
            [
                'name' => 'Gray Wolf', 'species' => 'Gray Wolf', 'scientific_name' => 'Canis lupus',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Carnivore', 'lifespan' => '6-8 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The gray wolf is the largest wild member of the dog family. Highly social, wolves live in packs with complex hierarchies and coordinate hunts with remarkable teamwork and communication.',
                'image' => '/images/animals/gray_wolf_1.png',
                'gallery' => json_encode(['/images/animals/gray_wolf_1.png', '/images/animals/gray_wolf_2.png']),
                'fun_facts' => json_encode(['Wolves can run up to 40 miles in a single day.', 'A wolf howl can be heard 10 miles away.', 'Wolves mate for life.']),
                'weight' => '45 kg', 'height' => '0.8 m', 'speed' => '65 km/h',
            ],
            [
                'name' => 'Black Bear', 'species' => 'American Black Bear', 'scientific_name' => 'Ursus americanus',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Omnivore', 'lifespan' => '20-25 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The American black bear is the most common bear in North America. Despite their name, they can be brown, cinnamon, or even white. They are excellent climbers and swimmers.',
                'image' => '/images/animals/black_bear_1.png',
                'gallery' => json_encode(['/images/animals/black_bear_1.png', '/images/animals/black_bear_2.png']),
                'fun_facts' => json_encode(['Black bears can smell food from 5 miles away.', 'They can run at 35 mph.', 'Cubs stay with mom for about 2 years.']),
                'weight' => '130 kg', 'height' => '0.9 m', 'speed' => '56 km/h',
            ],
            [
                'name' => 'White-Tailed Deer', 'species' => 'White-Tailed Deer', 'scientific_name' => 'Odocoileus virginianus',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Herbivore', 'lifespan' => '6-14 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The white-tailed deer is named for the white underside of its tail, which it raises like a flag when alarmed. They are graceful forest dwellers found across the Americas.',
                'image' => '/images/animals/deer_1.png',
                'gallery' => json_encode(['/images/animals/deer_1.png', '/images/animals/deer_2.png']),
                'fun_facts' => json_encode(['Deer can jump up to 10 feet high.', 'Male deer grow new antlers every year.', 'Fawns are born with white spots for camouflage.']),
                'weight' => '68 kg', 'height' => '1.0 m', 'speed' => '48 km/h',
            ],
            [
                'name' => 'Wild Boar', 'species' => 'Wild Boar', 'scientific_name' => 'Sus scrofa',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Omnivore', 'lifespan' => '15-20 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The wild boar is a tough and adaptable forest dweller. Ancestors of domestic pigs, they have coarse bristly hair, tusks, and an incredible sense of smell used to root out food from the forest floor.',
                'image' => '/images/animals/wild_boar_1.png',
                'gallery' => json_encode(['/images/animals/wild_boar_1.png', '/images/animals/wild_boar_2.png']),
                'fun_facts' => json_encode(['Wild boars can smell things buried 25 feet underground.', 'Piglets have striped coats for camouflage.', 'They are excellent swimmers.']),
                'weight' => '90 kg', 'height' => '0.75 m', 'speed' => '48 km/h',
            ],
            [
                'name' => 'Red Panda', 'species' => 'Red Panda', 'scientific_name' => 'Ailurus fulgens',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Herbivore', 'lifespan' => '8-12 years',
                'conservation_status' => 'Endangered',
                'description' => 'The red panda is a small arboreal mammal native to the eastern Himalayas and southwestern China. With its reddish-brown fur, bushy tail, and adorable face, it is often called the "firefox".',
                'image' => '/images/animals/red_panda_1.png',
                'gallery' => json_encode(['/images/animals/red_panda_1.png', '/images/animals/red_panda_2.png']),
                'fun_facts' => json_encode(['Red pandas were discovered 50 years before giant pandas.', 'Firefox browser is named after the red panda.', 'They use their bushy tail as a blanket.']),
                'weight' => '5 kg', 'height' => '0.3 m', 'speed' => '38 km/h',
            ],
            [
                'name' => 'Orangutan', 'species' => 'Bornean Orangutan', 'scientific_name' => 'Pongo pygmaeus',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Omnivore', 'lifespan' => '35-45 years',
                'conservation_status' => 'Critically Endangered',
                'description' => 'Orangutans are the largest arboreal mammals and share 97% of their DNA with humans. These gentle, intelligent apes are known for their remarkable tool use and problem-solving abilities.',
                'image' => '/images/animals/orangutan_1.png',
                'gallery' => json_encode(['/images/animals/orangutan_1.png', '/images/animals/orangutan_2.png']),
                'fun_facts' => json_encode(['Orangutans share 97% of DNA with humans.', 'They build a new sleeping nest every night.', 'Males develop large cheek pads called flanges.']),
                'weight' => '75 kg', 'height' => '1.3 m', 'speed' => '6 km/h',
            ],
            [
                'name' => 'Jaguar', 'species' => 'Jaguar', 'scientific_name' => 'Panthera onca',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Carnivore', 'lifespan' => '12-15 years',
                'conservation_status' => 'Near Threatened',
                'description' => 'The jaguar is the largest cat in the Americas and the third-largest in the world. Unlike most cats, jaguars love water and are excellent swimmers. Their powerful bite can crack turtle shells.',
                'image' => '/images/animals/jaguar_1.png',
                'gallery' => json_encode(['/images/animals/jaguar_1.png', '/images/animals/jaguar_2.png']),
                'fun_facts' => json_encode(['Jaguars have the strongest bite of all big cats.', 'They can see in the dark 6 times better than humans.', 'Black jaguars are called "black panthers".']),
                'weight' => '100 kg', 'height' => '0.75 m', 'speed' => '80 km/h',
            ],
            [
                'name' => 'Toucan', 'species' => 'Toco Toucan', 'scientific_name' => 'Ramphastos toco',
                'category' => 'Bird', 'habitat_id' => 1, 'diet' => 'Omnivore', 'lifespan' => '20 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The toco toucan is the largest and most iconic toucan species, known for its enormous colorful bill. Despite its size, the bill is remarkably light, made of keratin with a honeycomb structure inside.',
                'image' => '/images/animals/toucan_1.png',
                'gallery' => json_encode(['/images/animals/toucan_1.png', '/images/animals/toucan_2.png']),
                'fun_facts' => json_encode(['A toucan\'s bill can be one-third of its body length.', 'They regulate body temperature through their bills.', 'Toucans sleep by tucking their bill over their back.']),
                'weight' => '0.7 kg', 'height' => '0.6 m', 'speed' => '60 km/h',
            ],
            [
                'name' => 'Scarlet Macaw', 'species' => 'Scarlet Macaw', 'scientific_name' => 'Ara macao',
                'category' => 'Bird', 'habitat_id' => 1, 'diet' => 'Herbivore', 'lifespan' => '40-50 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The scarlet macaw is one of the most beautiful parrots in the world, with vibrant red, yellow, and blue plumage. They are highly intelligent and can learn to mimic human speech.',
                'image' => '/images/animals/scarlet-macaw-1.jpg',
                'gallery' => json_encode(['/images/animals/scarlet-macaw-1.jpg', '/images/animals/scarlet-macaw-2.jpg']),
                'fun_facts' => json_encode(['Macaws can live up to 75 years in captivity.', 'They mate for life.', 'Macaws eat clay to neutralize toxins from fruits.']),
                'weight' => '1 kg', 'height' => '0.85 m', 'speed' => '56 km/h',
            ],
            [
                'name' => 'Green Tree Python', 'species' => 'Green Tree Python', 'scientific_name' => 'Morelia viridis',
                'category' => 'Reptile', 'habitat_id' => 1, 'diet' => 'Carnivore', 'lifespan' => '15-20 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The green tree python is a strikingly beautiful non-venomous snake found in tropical rainforests. They spend most of their lives coiled on branches, ambushing prey with lightning-fast strikes.',
                'image' => '/images/animals/green-tree-python-1.jpg',
                'gallery' => json_encode(['/images/animals/green-tree-python-1.jpg', '/images/animals/green-tree-python-2.jpg']),
                'fun_facts' => json_encode(['Babies are bright yellow or red, turning green as adults.', 'They coil around branches in a saddle position.', 'They have heat-sensing pits to detect warm-blooded prey.']),
                'weight' => '1.6 kg', 'height' => '1.8 m (length)', 'speed' => '5 km/h',
            ],
            [
                'name' => 'Chameleon', 'species' => 'Panther Chameleon', 'scientific_name' => 'Furcifer pardalis',
                'category' => 'Reptile', 'habitat_id' => 1, 'diet' => 'Carnivore', 'lifespan' => '5-7 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The panther chameleon is renowned for its extraordinary color-changing ability and independently rotating eyes. Native to Madagascar, it is one of the most colorful reptiles in the world.',
                'image' => '/images/animals/chameleon-1.jpg',
                'gallery' => json_encode(['/images/animals/chameleon-1.jpg', '/images/animals/chameleon-2.jpg']),
                'fun_facts' => json_encode(['Chameleons can move their eyes independently in different directions.', 'Their tongue is twice their body length.', 'Color change is used for communication, not just camouflage.']),
                'weight' => '0.18 kg', 'height' => '0.5 m (length)', 'speed' => '3 km/h',
            ],
            [
                'name' => 'Gorilla', 'species' => 'Western Lowland Gorilla', 'scientific_name' => 'Gorilla gorilla gorilla',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Herbivore', 'lifespan' => '35-40 years',
                'conservation_status' => 'Critically Endangered',
                'description' => 'The western lowland gorilla is the most numerous gorilla subspecies. Led by a dominant silverback male, these gentle giants are highly intelligent and share 98.3% of their DNA with humans.',
                'image' => '/images/animals/gorilla-1.jpg',
                'gallery' => json_encode(['/images/animals/gorilla-1.jpg', '/images/animals/gorilla-2.jpg']),
                'fun_facts' => json_encode(['Gorillas share 98.3% of DNA with humans.', 'Silverbacks can lift 10 times their body weight.', 'They laugh when tickled, just like humans.']),
                'weight' => '160 kg', 'height' => '1.7 m', 'speed' => '40 km/h',
            ],
            [
                'name' => 'Sloth', 'species' => 'Three-Toed Sloth', 'scientific_name' => 'Bradypus variegatus',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Herbivore', 'lifespan' => '20-30 years',
                'conservation_status' => 'Least Concern',
                'description' => 'Sloths are famously slow-moving arboreal mammals from Central and South American rainforests. They spend nearly their entire lives hanging upside down in trees, sleeping up to 20 hours a day.',
                'image' => '/images/animals/sloth-1.jpg',
                'gallery' => json_encode(['/images/animals/sloth-1.jpg', '/images/animals/sloth-2.jpg']),
                'fun_facts' => json_encode(['Sloths are 3x faster in water than on land.', 'Algae grows on their fur, giving them green camouflage.', 'They only come down from trees once a week to poop.']),
                'weight' => '4.5 kg', 'height' => '0.6 m', 'speed' => '0.24 km/h',
            ],
            [
                'name' => 'Poison Dart Frog', 'species' => 'Blue Poison Dart Frog', 'scientific_name' => 'Dendrobates tinctorius azureus',
                'category' => 'Amphibian', 'habitat_id' => 1, 'diet' => 'Carnivore', 'lifespan' => '10-15 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The blue poison dart frog is an electric-blue amphibian found in South American rainforests. Indigenous people historically used their toxic secretions to poison the tips of blowgun darts for hunting.',
                'image' => '/images/animals/poison-dart-frog-1.jpg',
                'gallery' => json_encode(['/images/animals/poison-dart-frog-1.jpg', '/images/animals/poison-dart-frog-2.jpg']),
                'fun_facts' => json_encode(['One frog has enough poison to kill 10 men.', 'Their bright color warns predators they are toxic.', 'In captivity, they lose their toxicity due to diet changes.']),
                'weight' => '0.008 kg', 'height' => '0.05 m', 'speed' => '2 km/h',
            ],
            [
                'name' => 'Clouded Leopard', 'species' => 'Clouded Leopard', 'scientific_name' => 'Neofelis nebulosa',
                'category' => 'Mammal', 'habitat_id' => 1, 'diet' => 'Carnivore', 'lifespan' => '11-17 years',
                'conservation_status' => 'Vulnerable',
                'description' => 'The clouded leopard is a secretive wild cat of Southeast Asian forests, named for the large cloud-shaped markings on its coat. It has the longest canine teeth relative to body size of any living cat.',
                'image' => '/images/animals/clouded-leopard-1.jpg',
                'gallery' => json_encode(['/images/animals/clouded-leopard-1.jpg', '/images/animals/clouded-leopard-2.jpg']),
                'fun_facts' => json_encode(['They can climb down trees headfirst like squirrels.', 'Their tail is as long as their body for balance.', 'They can hang from branches by their hind feet.']),
                'weight' => '20 kg', 'height' => '0.5 m', 'speed' => '64 km/h',
            ],
            [
                'name' => 'Woodpecker', 'species' => 'Pileated Woodpecker', 'scientific_name' => 'Dryocopus pileatus',
                'category' => 'Bird', 'habitat_id' => 1, 'diet' => 'Omnivore', 'lifespan' => '12 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The pileated woodpecker is one of the largest forest birds in North America, recognized by its flaming red crest. Its powerful drumming on trees can be heard from far away as it excavates for insects.',
                'image' => '/images/animals/woodpecker-1.jpg',
                'gallery' => json_encode(['/images/animals/woodpecker-1.jpg', '/images/animals/woodpecker-2.jpg']),
                'fun_facts' => json_encode(['Woodpeckers peck up to 20 times per second.', 'Their skulls have built-in shock absorbers.', 'Their tongue wraps around the inside of their skull.']),
                'weight' => '0.3 kg', 'height' => '0.45 m', 'speed' => '25 km/h',
            ],
        ];

        foreach ($animals as $animal) {
            Animal::create($animal);
        }
    }
}
