<?php

namespace Database\Seeders;

use App\Models\Animal;
use Illuminate\Database\Seeder;

class OceanAnimalSeeder extends Seeder
{
    public function run(): void
    {
        $animals = [
            [
                'name'                => 'Great White Shark',
                'species'             => 'Great White Shark',
                'scientific_name'     => 'Carcharodon carcharias',
                'category'            => 'Fish',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '70+ years',
                'conservation_status' => 'Vulnerable',
                'description'         => 'The great white shark is the world\'s largest predatory fish, reaching up to 6 metres in length. Despite its fearsome reputation, attacks on humans are rare — it is far more likely to be the victim, as populations are declining due to finning and bycatch.',
                'image'               => '/images/animals/great-white-shark-1.jpg',
                'gallery'             => json_encode(['/images/animals/great-white-shark-1.jpg', '/images/animals/great-white-shark-2.jpg']),
                'fun_facts'           => json_encode([
                    'Great whites can detect a single drop of blood in 100 litres of water.',
                    'They can breach completely out of the water when hunting seals.',
                    'Their teeth are replaced throughout their lifetime — up to 30,000 teeth!',
                ]),
                'weight' => '1,100 kg', 'height' => '6 m (length)', 'speed' => '56 km/h',
            ],
            [
                'name'                => 'Blue Whale',
                'species'             => 'Blue Whale',
                'scientific_name'     => 'Balaenoptera musculus',
                'category'            => 'Mammal',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '80-90 years',
                'conservation_status' => 'Endangered',
                'description'         => 'The blue whale is the largest animal ever known to have lived on Earth. A fully grown blue whale can reach 30 metres and weigh up to 200 tonnes. Despite being massive, it feeds almost exclusively on tiny krill, consuming up to 40 million of them each day.',
                'image'               => '/images/animals/blue-whale-1.jpg',
                'gallery'             => json_encode(['/images/animals/blue-whale-1.jpg', '/images/animals/blue-whale-2.jpg']),
                'fun_facts'           => json_encode([
                    'A blue whale\'s heart is the size of a small car.',
                    'Their call can be heard 1,600 km away underwater.',
                    'A blue whale calf gains 90 kg per day on its mother\'s milk.',
                ]),
                'weight' => '200,000 kg', 'height' => '30 m (length)', 'speed' => '46 km/h',
            ],
            [
                'name'                => 'Bottlenose Dolphin',
                'species'             => 'Common Bottlenose Dolphin',
                'scientific_name'     => 'Tursiops truncatus',
                'category'            => 'Mammal',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '40-60 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'Bottlenose dolphins are among the most intelligent animals on the planet. They live in pods, communicate with complex clicks and whistles, and have even been observed using tools — carrying sponges to protect their snouts while foraging on the seafloor.',
                'image'               => '/images/animals/dolphin-1.jpg',
                'gallery'             => json_encode(['/images/animals/dolphin-1.jpg', '/images/animals/dolphin-2.jpg']),
                'fun_facts'           => json_encode([
                    'Dolphins sleep with one eye open, resting half their brain at a time.',
                    'Each dolphin has a unique signature whistle — like a name.',
                    'They can swim up to 60 km/h in short bursts.',
                ]),
                'weight' => '300 kg', 'height' => '2.5 m (length)', 'speed' => '60 km/h',
            ],
            [
                'name'                => 'Giant Pacific Octopus',
                'species'             => 'Giant Pacific Octopus',
                'scientific_name'     => 'Enteroctopus dofleini',
                'category'            => 'Invertebrate',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '3-5 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The giant Pacific octopus is the largest octopus species in the world, with arms that can span up to 4.3 metres. It is extraordinarily intelligent, capable of opening jars, solving puzzles, and even recognising individual human faces.',
                'image'               => '/images/animals/octopus-1.jpg',
                'gallery'             => json_encode(['/images/animals/octopus-1.jpg', '/images/animals/octopus-2.jpg']),
                'fun_facts'           => json_encode([
                    'Octopuses have three hearts and blue blood.',
                    'They can change colour and texture within milliseconds.',
                    'Each arm has its own mini-brain and can act independently.',
                ]),
                'weight' => '15 kg', 'height' => '4.3 m (arm span)', 'speed' => '40 km/h',
            ],
            [
                'name'                => 'Green Sea Turtle',
                'species'             => 'Green Sea Turtle',
                'scientific_name'     => 'Chelonia mydas',
                'category'            => 'Reptile',
                'habitat_id'          => 3,
                'diet'                => 'Herbivore',
                'lifespan'            => '80+ years',
                'conservation_status' => 'Endangered',
                'description'         => 'The green sea turtle is one of the largest sea turtles and the only herbivorous one as an adult. They migrate thousands of kilometres between feeding grounds and the beaches where they nest — returning to the exact beach where they were born.',
                'image'               => '/images/animals/sea-turtle-1.jpg',
                'gallery'             => json_encode(['/images/animals/sea-turtle-1.jpg', '/images/animals/sea-turtle-2.jpg']),
                'fun_facts'           => json_encode([
                    'Sea turtles navigate using Earth\'s magnetic field.',
                    'They can hold their breath for up to 7 hours while sleeping.',
                    'Temperature determines the sex of hatchlings — warmer = female.',
                ]),
                'weight' => '160 kg', 'height' => '1.5 m (length)', 'speed' => '35 km/h',
            ],
            [
                'name'                => 'Clownfish',
                'species'             => 'Ocellaris Clownfish',
                'scientific_name'     => 'Amphiprion ocellaris',
                'category'            => 'Fish',
                'habitat_id'          => 3,
                'diet'                => 'Omnivore',
                'lifespan'            => '6-10 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'Made famous by the film "Finding Nemo", the clownfish lives in a mutualistic relationship with sea anemones. The anemone protects the clownfish with its stinging tentacles, while the clownfish chases away parasitic fish and its waste fertilises the anemone.',
                'image'               => '/images/animals/clownfish-1.jpg',
                'gallery'             => json_encode(['/images/animals/clownfish-1.jpg', '/images/animals/clownfish-2.jpg']),
                'fun_facts'           => json_encode([
                    'All clownfish are born male — the dominant one becomes female.',
                    'They are immune to the anemone\'s deadly sting.',
                    'Clownfish never stray more than a few metres from their anemone.',
                ]),
                'weight' => '0.01 kg', 'height' => '0.11 m (length)', 'speed' => '4 km/h',
            ],
            [
                'name'                => 'Oceanic Manta Ray',
                'species'             => 'Oceanic Manta Ray',
                'scientific_name'     => 'Mobula birostris',
                'category'            => 'Fish',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '40-50 years',
                'conservation_status' => 'Vulnerable',
                'description'         => 'The oceanic manta ray is the world\'s largest ray, with a wingspan of up to 7 metres. Despite their enormous size, they feed on tiny plankton filtered through their gill rakers. They are highly intelligent and have the largest brain-to-body ratio of any fish.',
                'image'               => '/images/animals/manta-ray-1.jpg',
                'gallery'             => json_encode(['/images/animals/manta-ray-1.jpg', '/images/animals/manta-ray-2.jpg']),
                'fun_facts'           => json_encode([
                    'Manta rays have the largest brain of any fish.',
                    'They visit "cleaning stations" where small fish remove parasites.',
                    'They can breach fully out of the water, possibly to communicate.',
                ]),
                'weight' => '1,350 kg', 'height' => '7 m (wingspan)', 'speed' => '24 km/h',
            ],
            [
                'name'                => 'Hammerhead Shark',
                'species'             => 'Great Hammerhead Shark',
                'scientific_name'     => 'Sphyrna mokarran',
                'category'            => 'Fish',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '20-30 years',
                'conservation_status' => 'Critically Endangered',
                'description'         => 'The hammerhead shark is instantly recognisable by its wide, hammer-shaped head called a "cephalofoil". This unique shape allows its eyes and nostrils to be widely spaced, giving it excellent 360-degree vision and an enhanced ability to detect electrical fields from prey.',
                'image'               => '/images/animals/hammerhead-shark-1.jpg',
                'gallery'             => json_encode(['/images/animals/hammerhead-shark-1.jpg', '/images/animals/hammerhead-shark-2.jpg']),
                'fun_facts'           => json_encode([
                    'Hammerheads can detect the heartbeat of buried stingrays.',
                    'They have nearly 360-degree vision — they can see above and below simultaneously.',
                    'Great hammerheads are cannibalistic and must keep swimming to survive.',
                ]),
                'weight' => '450 kg', 'height' => '6 m (length)', 'speed' => '48 km/h',
            ],
            [
                'name'                => 'Seahorse',
                'species'             => 'Lined Seahorse',
                'scientific_name'     => 'Hippocampus erectus',
                'category'            => 'Fish',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '1-5 years',
                'conservation_status' => 'Vulnerable',
                'description'         => 'Seahorses are among the most unique fish in the ocean. They swim upright, lack a stomach, and are monogamous. Most remarkably, it is the male that carries and gives birth to the young — up to 1,500 at a time — making them one of the few species where the male becomes pregnant.',
                'image'               => '/images/animals/seahorse-1.jpg',
                'gallery'             => json_encode(['/images/animals/seahorse-1.jpg', '/images/animals/seahorse-2.jpg']),
                'fun_facts'           => json_encode([
                    'Male seahorses give birth — not females.',
                    'They are the slowest fish, moving at just 1.5 metres per hour.',
                    'Seahorses have no stomach — food passes through so fast they must eat constantly.',
                ]),
                'weight' => '0.001 kg', 'height' => '0.35 m', 'speed' => '0.0015 km/h',
            ],
            [
                'name'                => 'Lionfish',
                'species'             => 'Red Lionfish',
                'scientific_name'     => 'Pterois volitans',
                'category'            => 'Fish',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '10-15 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'The lionfish is one of the most venomous fish in the ocean, armed with 18 needle-like spines loaded with toxic venom. Native to the Indo-Pacific, it has become an invasive species in the Atlantic where it devastates reef ecosystems as it has no natural predators.',
                'image'               => '/images/animals/lionfish-1.jpg',
                'gallery'             => json_encode(['/images/animals/lionfish-1.jpg', '/images/animals/lionfish-2.jpg']),
                'fun_facts'           => json_encode([
                    'Lionfish can eat prey up to twice their own size.',
                    'They corner prey by herding them with their pectoral fins.',
                    'Their sting is agonising but not typically fatal to humans.',
                ]),
                'weight' => '1.2 kg', 'height' => '0.38 m (length)', 'speed' => '12 km/h',
            ],
            [
                'name'                => 'Moon Jellyfish',
                'species'             => 'Moon Jellyfish',
                'scientific_name'     => 'Aurelia aurita',
                'category'            => 'Invertebrate',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '12-18 months',
                'conservation_status' => 'Least Concern',
                'description'         => 'The moon jellyfish is one of the most common jellyfish in the world, identifiable by its translucent bell and four horseshoe-shaped gonads. It has no brain, heart, or bones, yet has survived for over 500 million years — outlasting dinosaurs and five mass extinctions.',
                'image'               => '/images/animals/jellyfish-1.jpg',
                'gallery'             => json_encode(['/images/animals/jellyfish-1.jpg', '/images/animals/jellyfish-2.jpg']),
                'fun_facts'           => json_encode([
                    'Jellyfish have no brain, heart, or blood.',
                    'They are 95% water.',
                    'Some species are biologically immortal — reverting to their juvenile state when stressed.',
                ]),
                'weight' => '0.1 kg', 'height' => '0.4 m (bell diameter)', 'speed' => '8 km/h',
            ],
            [
                'name'                => 'Orca',
                'species'             => 'Killer Whale',
                'scientific_name'     => 'Orcinus orca',
                'category'            => 'Mammal',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '50-80 years',
                'conservation_status' => 'Data Deficient',
                'description'         => 'Orcas, or killer whales, are the largest members of the dolphin family and apex predators of the ocean. They live in tight-knit family pods with rich cultural traditions — different pods even speak different "dialects". They are the only animals known to prey on great white sharks.',
                'image'               => '/images/animals/orca-1.jpg',
                'gallery'             => json_encode(['/images/animals/orca-1.jpg', '/images/animals/orca-2.jpg']),
                'fun_facts'           => json_encode([
                    'Orcas are the only predator that hunts great white sharks.',
                    'They use coordinated hunting strategies — like a wolf pack of the sea.',
                    'Females can live past 90 years and lead their family pod as matriarchs.',
                ]),
                'weight' => '5,400 kg', 'height' => '8 m (length)', 'speed' => '56 km/h',
            ],
            [
                'name'                => 'Starfish',
                'species'             => 'Common Starfish',
                'scientific_name'     => 'Asterias rubens',
                'category'            => 'Invertebrate',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '35 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'Starfish, or sea stars, are iconic echinoderms found in oceans worldwide. They have no brain and no blood, yet they can regenerate lost arms completely. They eat by extruding their stomachs outside their bodies and digesting prey externally.',
                'image'               => '/images/animals/starfish-1.jpg',
                'gallery'             => json_encode(['/images/animals/starfish-1.jpg', '/images/animals/starfish-2.jpg']),
                'fun_facts'           => json_encode([
                    'Starfish can regrow an entire new body from a single arm.',
                    'They have hundreds of tiny tube feet instead of legs.',
                    'Their stomach can squeeze out through their mouth to digest food externally.',
                ]),
                'weight' => '0.5 kg', 'height' => '0.3 m (diameter)', 'speed' => '0.09 km/h',
            ],
            [
                'name'                => 'Cuttlefish',
                'species'             => 'Common Cuttlefish',
                'scientific_name'     => 'Sepia officinalis',
                'category'            => 'Invertebrate',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '1-2 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'Cuttlefish are masters of camouflage and one of the most intelligent invertebrates. Despite being colour-blind, they can produce stunning, complex colour patterns across their skin in milliseconds. Males use elaborate hypnotic displays to attract females and confuse rivals simultaneously.',
                'image'               => '/images/animals/cuttlefish-1.jpg',
                'gallery'             => json_encode(['/images/animals/cuttlefish-1.jpg', '/images/animals/cuttlefish-2.jpg']),
                'fun_facts'           => json_encode([
                    'Cuttlefish are colour-blind yet produce the most complex colour displays in the animal kingdom.',
                    'They have W-shaped pupils that give them a wide field of view.',
                    'Their ink was historically used as "sepia" ink for writing and art.',
                ]),
                'weight' => '4 kg', 'height' => '0.45 m (length)', 'speed' => '11 km/h',
            ],
            [
                'name'                => 'Humpback Whale',
                'species'             => 'Humpback Whale',
                'scientific_name'     => 'Megaptera novaeangliae',
                'category'            => 'Mammal',
                'habitat_id'          => 3,
                'diet'                => 'Carnivore',
                'lifespan'            => '45-100 years',
                'conservation_status' => 'Least Concern',
                'description'         => 'Humpback whales are celebrated for their hauntingly beautiful songs and spectacular acrobatic breaches. Males compose complex, evolving songs that can last hours and be heard hundreds of kilometres away. They undertake one of the longest migrations of any mammal — up to 25,000 km round-trip.',
                'image'               => '/images/animals/humpback-whale-1.jpg',
                'gallery'             => json_encode(['/images/animals/humpback-whale-1.jpg', '/images/animals/humpback-whale-2.jpg']),
                'fun_facts'           => json_encode([
                    'Only male humpbacks sing — and the song evolves each year.',
                    'They create "bubble-net" traps to herd fish to the surface.',
                    'A humpback whale\'s flippers are the longest appendage of any animal — up to 5 m.',
                ]),
                'weight' => '36,000 kg', 'height' => '16 m (length)', 'speed' => '27 km/h',
            ],
        ];

        foreach ($animals as $animal) {
            Animal::create($animal);
        }
    }
}
