<?php

namespace Database\Seeders;

use App\Models\Animal;
use Illuminate\Database\Seeder;

class SavannahAnimalSeeder extends Seeder
{
    public function run(): void
    {
        $animals = [
            [
                'name' => 'African Lion', 'species' => 'African Lion', 'scientific_name' => 'Panthera leo',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Carnivore', 'lifespan' => '10-14 years',
                'conservation_status' => 'Vulnerable',
                'description' => 'The African lion is the second-largest cat in the world and the only truly social big cat. Prides of up to 40 lions are led by females who do 90% of the hunting. The male\'s iconic mane signals health and genetic quality — darker manes indicate older, healthier males.',
                'image' => '/images/animals/lion-1.jpg',
                'gallery' => json_encode(['/images/animals/lion-1.jpg', '/images/animals/lion-2.jpg']),
                'fun_facts' => json_encode(['A lion\'s roar can be heard 8 km away.', 'Lions sleep up to 20 hours per day.', 'Lionesses do up to 90% of the pride\'s hunting.']),
                'weight' => '190 kg', 'height' => '1.2 m', 'speed' => '80 km/h',
            ],
            [
                'name' => 'African Elephant', 'species' => 'African Bush Elephant', 'scientific_name' => 'Loxodonta africana',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Herbivore', 'lifespan' => '60-70 years',
                'conservation_status' => 'Vulnerable',
                'description' => 'The African elephant is the largest land animal on Earth. Led by a matriarch, elephant herds display remarkable intelligence and emotional depth — mourning their dead and recognising themselves in mirrors. They are a keystone species, shaping their entire ecosystem by creating water holes and dispersing seeds.',
                'image' => '/images/animals/elephant-1.jpg',
                'gallery' => json_encode(['/images/animals/elephant-1.jpg', '/images/animals/elephant-2.jpg']),
                'fun_facts' => json_encode(['Elephants can recognise themselves in a mirror.', 'They mourn their dead and visit bones of deceased herd members.', 'An elephant\'s trunk has 40,000 muscles — more than the human body.']),
                'weight' => '6,000 kg', 'height' => '3.3 m', 'speed' => '40 km/h',
            ],
            [
                'name' => 'Cheetah', 'species' => 'Cheetah', 'scientific_name' => 'Acinonyx jubatus',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Carnivore', 'lifespan' => '10-12 years',
                'conservation_status' => 'Vulnerable',
                'description' => 'The cheetah is the fastest land animal on Earth, capable of accelerating from 0 to 100 km/h in just 3 seconds. Unlike other big cats, cheetahs cannot roar — they purr, chirp, and even bark. Their distinctive black "tear marks" below their eyes reduce sun glare, acting like built-in sunglasses during high-speed chases.',
                'image' => '/images/animals/cheetah-1.jpg',
                'gallery' => json_encode(['/images/animals/cheetah-1.jpg', '/images/animals/cheetah-2.jpg']),
                'fun_facts' => json_encode(['Cheetahs accelerate from 0-100 km/h in 3 seconds.', 'They cannot roar — they chirp, purr and bark instead.', 'Their semi-retractable claws grip the ground like running spikes.']),
                'weight' => '65 kg', 'height' => '0.9 m', 'speed' => '120 km/h',
            ],
            [
                'name' => 'Giraffe', 'species' => 'Masai Giraffe', 'scientific_name' => 'Giraffa camelopardalis tippelskirchii',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Herbivore', 'lifespan' => '25 years',
                'conservation_status' => 'Vulnerable',
                'description' => 'The giraffe is the tallest living terrestrial animal on Earth, with males reaching up to 5.7 metres tall. Their extraordinary necks — which contain the same 7 vertebrae as a human neck — allow them to feed on acacia leaves no other herbivore can reach. Their 45 cm purple tongue is tough enough to strip thorns.',
                'image' => '/images/animals/giraffe-1.jpg',
                'gallery' => json_encode(['/images/animals/giraffe-1.jpg', '/images/animals/giraffe-2.jpg']),
                'fun_facts' => json_encode(['Giraffes have the same 7 neck vertebrae as humans — just much longer.', 'Their heart weighs 11 kg and pumps blood 2 metres upward to the brain.', 'Giraffes sleep only 30 minutes per day in short 5-minute naps.']),
                'weight' => '1,200 kg', 'height' => '5.7 m', 'speed' => '60 km/h',
            ],
            [
                'name' => 'Plains Zebra', 'species' => 'Plains Zebra', 'scientific_name' => 'Equus quagga',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Herbivore', 'lifespan' => '25 years',
                'conservation_status' => 'Near Threatened',
                'description' => 'Zebras are iconic African mammals whose bold black-and-white stripes are as unique as human fingerprints. Science has recently shown their stripes evolved to deter biting flies — the alternating pattern confuses insects trying to land. Zebras form the largest land migration on Earth alongside wildebeest.',
                'image' => '/images/animals/zebra-1.jpg',
                'gallery' => json_encode(['/images/animals/zebra-1.jpg', '/images/animals/zebra-2.jpg']),
                'fun_facts' => json_encode(['No two zebras have the same stripe pattern.', 'Their stripes deter biting flies by disrupting their landing approach.', 'Zebra foals can run within hours of birth.']),
                'weight' => '350 kg', 'height' => '1.5 m', 'speed' => '65 km/h',
            ],
            [
                'name' => 'Hippopotamus', 'species' => 'Common Hippopotamus', 'scientific_name' => 'Hippopotamus amphibius',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Herbivore', 'lifespan' => '40-50 years',
                'conservation_status' => 'Vulnerable',
                'description' => 'Despite their docile appearance, hippos are Africa\'s most dangerous large land animal. They spend up to 16 hours a day submerged in rivers and lakes to keep cool, and their skin secretes a natural reddish oil that acts as sunscreen and antibiotic. Hippos are more closely related to whales than to pigs.',
                'image' => '/images/animals/hippo-1.jpg',
                'gallery' => json_encode(['/images/animals/hippo-1.jpg', '/images/animals/hippo-2.jpg']),
                'fun_facts' => json_encode(['Hippos are more closely related to whales than to pigs.', 'Their "blood sweat" is a natural sunscreen and antibiotic.', 'Hippos can run faster than humans on land — up to 30 km/h.']),
                'weight' => '3,000 kg', 'height' => '1.5 m', 'speed' => '30 km/h',
            ],
            [
                'name' => 'Cape Buffalo', 'species' => 'African Buffalo', 'scientific_name' => 'Syncerus caffer',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Herbivore', 'lifespan' => '20-25 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The Cape buffalo is one of Africa\'s most formidable animals, nicknamed "Black Death" by hunters. It is the only member of the Big Five that has never been domesticated. Buffalo herds practise a form of democracy — when deciding which direction to travel, females vote by standing and gazing in their preferred direction.',
                'image' => '/images/animals/cape-buffalo-1.jpg',
                'gallery' => json_encode(['/images/animals/cape-buffalo-1.jpg', '/images/animals/cape-buffalo-2.jpg']),
                'fun_facts' => json_encode(['Buffalo herds vote on direction of travel by majority gaze.', 'They have been known to ambush and kill lions that threaten them.', 'A herd can have up to 1,000 members.']),
                'weight' => '750 kg', 'height' => '1.7 m', 'speed' => '57 km/h',
            ],
            [
                'name' => 'Wildebeest', 'species' => 'Blue Wildebeest', 'scientific_name' => 'Connochaetes taurinus',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Herbivore', 'lifespan' => '20 years',
                'conservation_status' => 'Least Concern',
                'description' => 'Wildebeest are the stars of the Great Migration — the largest movement of land animals on Earth. Over 1.5 million wildebeest travel a 1,200 km circular route through the Serengeti following the rains. The dramatic Mara River crossings, where they brave crocodiles to reach fresh pasture, are one of nature\'s greatest spectacles.',
                'image' => '/images/animals/wildebeest-1.jpg',
                'gallery' => json_encode(['/images/animals/wildebeest-1.jpg', '/images/animals/wildebeest-2.jpg']),
                'fun_facts' => json_encode(['1.5 million wildebeest migrate 1,200 km annually.', 'Calves can run within minutes of birth — essential for survival.', 'Wildebeest droppings fertilise the Serengeti, sustaining its grasslands.']),
                'weight' => '270 kg', 'height' => '1.45 m', 'speed' => '80 km/h',
            ],
            [
                'name' => 'Spotted Hyena', 'species' => 'Spotted Hyena', 'scientific_name' => 'Crocuta crocuta',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Carnivore', 'lifespan' => '20-25 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The spotted hyena is one of Africa\'s most misunderstood animals. Far from being mere scavengers, hyenas are highly effective pack hunters that kill up to 95% of their own food. They have the strongest bite force of any land mammal relative to body size, capable of crushing elephant bones to extract marrow.',
                'image' => '/images/animals/hyena-1.jpg',
                'gallery' => json_encode(['/images/animals/hyena-1.jpg', '/images/animals/hyena-2.jpg']),
                'fun_facts' => json_encode(['Hyenas hunt 95% of their own food — they are not just scavengers.', 'Their "laugh" is actually a contact call, not an expression of amusement.', 'Hyena clans are led by females — the most socially complex carnivore society.']),
                'weight' => '70 kg', 'height' => '0.9 m', 'speed' => '60 km/h',
            ],
            [
                'name' => 'Warthog', 'species' => 'Common Warthog', 'scientific_name' => 'Phacochoerus africanus',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Omnivore', 'lifespan' => '15 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The warthog is a tough, adaptable member of the pig family that thrives in the African savannah. Their distinctive tusks and facial warts — which are actually tough skin pads that protect their face during fights — give them their rugged appearance. When fleeing danger, they run with their tail raised straight up like an antenna.',
                'image' => '/images/animals/warthog-1.jpg',
                'gallery' => json_encode(['/images/animals/warthog-1.jpg', '/images/animals/warthog-2.jpg']),
                'fun_facts' => json_encode(['Warthogs run with their tails raised straight up like antennas.', 'Their "warts" are protective skin pads, not actual warts.', 'They kneel on their front legs to graze — their necks are too short to reach the ground.']),
                'weight' => '100 kg', 'height' => '0.75 m', 'speed' => '50 km/h',
            ],
            [
                'name' => 'Olive Baboon', 'species' => 'Olive Baboon', 'scientific_name' => 'Papio anubis',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Omnivore', 'lifespan' => '20-30 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The olive baboon is one of the most wide-ranging primates in Africa. These highly intelligent, opportunistic omnivores live in complex hierarchical troops of up to 150 individuals. They are one of the few non-human primates observed hunting cooperatively and using tools in the wild.',
                'image' => '/images/animals/baboon-1.jpg',
                'gallery' => json_encode(['/images/animals/baboon-1.jpg', '/images/animals/baboon-2.jpg']),
                'fun_facts' => json_encode(['Baboon troops can have over 150 members with complex social hierarchies.', 'Juveniles stress-eat when upset — just like humans.', 'They cooperate to mob and chase away cheetahs and leopards.']),
                'weight' => '30 kg', 'height' => '0.75 m', 'speed' => '45 km/h',
            ],
            [
                'name' => 'African Wild Dog', 'species' => 'African Wild Dog', 'scientific_name' => 'Lycaon pictus',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Carnivore', 'lifespan' => '10-12 years',
                'conservation_status' => 'Endangered',
                'description' => 'The African wild dog — also called the painted dog for its unique mottled coat — is Africa\'s most successful predator. With a hunt success rate of 80% (lions achieve only 30%), they use stamina and remarkable teamwork to run prey to exhaustion. They care for their sick and injured, regurgitating food for pack members that couldn\'t hunt.',
                'image' => '/images/animals/wild-dog-1.jpg',
                'gallery' => json_encode(['/images/animals/wild-dog-1.jpg', '/images/animals/wild-dog-2.jpg']),
                'fun_facts' => json_encode(['African wild dogs have an 80% hunt success rate — the best of any predator.', 'They sneeze to vote on whether the pack should go hunting.', 'No two wild dogs have the same coat pattern.']),
                'weight' => '30 kg', 'height' => '0.75 m', 'speed' => '72 km/h',
            ],
            [
                'name' => 'Impala', 'species' => 'Common Impala', 'scientific_name' => 'Aepyceros melampus',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Herbivore', 'lifespan' => '12-15 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The impala is one of Africa\'s most graceful and athletic antelopes, capable of leaping 3 metres high and 10 metres forward in a single bound. These explosive jumps — sometimes with no predator in sight — confuse predators with their unpredictability. Impalas are the most abundant antelope in East Africa.',
                'image' => '/images/animals/impala-1.jpg',
                'gallery' => json_encode(['/images/animals/impala-1.jpg', '/images/animals/impala-2.jpg']),
                'fun_facts' => json_encode(['Impalas can leap 3 m high and 10 m forward.', 'They sometimes leap for no reason — to confuse potential predators.', 'Their distinctive black markings on the hindquarters may help herd members follow each other.']),
                'weight' => '65 kg', 'height' => '0.95 m', 'speed' => '90 km/h',
            ],
            [
                'name' => 'Ostrich', 'species' => 'Common Ostrich', 'scientific_name' => 'Struthio camelus',
                'category' => 'Bird', 'habitat_id' => 5, 'diet' => 'Omnivore', 'lifespan' => '40-45 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The ostrich is the world\'s largest living bird and the fastest running bird on Earth. Despite having wings, it cannot fly — but it can sprint at 70 km/h and maintain 50 km/h for 30 minutes. Its powerful legs deliver kicks strong enough to kill a lion. The "head in sand" behaviour is a myth — they lie flat to hide from predators.',
                'image' => '/images/animals/ostrich-1.jpg',
                'gallery' => json_encode(['/images/animals/ostrich-1.jpg', '/images/animals/ostrich-2.jpg']),
                'fun_facts' => json_encode(['Ostriches can sprint at 70 km/h — the fastest bird on land.', 'Their eye is bigger than their brain.', 'An ostrich kick can kill a lion.']),
                'weight' => '145 kg', 'height' => '2.7 m', 'speed' => '70 km/h',
            ],
            [
                'name' => 'White Rhinoceros', 'species' => 'Southern White Rhinoceros', 'scientific_name' => 'Ceratotherium simum simum',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Herbivore', 'lifespan' => '40-50 years',
                'conservation_status' => 'Near Threatened',
                'description' => 'The white rhinoceros is the largest rhino species and the third-largest land animal on Earth. Despite their size, they are surprisingly fast and agile. Their "white" name has nothing to do with colour — it derives from the Afrikaans word "wyd" meaning wide, referring to their wide, flat lips adapted for grazing on grass.',
                'image' => '/images/animals/rhino-1.jpg',
                'gallery' => json_encode(['/images/animals/rhino-1.jpg', '/images/animals/rhino-2.jpg']),
                'fun_facts' => json_encode(['"White" rhino comes from Afrikaans "wyd" (wide) — for their wide mouths.', 'Their horn is made of keratin — the same material as human fingernails.', 'Rhinos roll in mud to cool down and protect skin from parasites.']),
                'weight' => '2,300 kg', 'height' => '1.85 m', 'speed' => '50 km/h',
            ],
            [
                'name' => 'Leopard', 'species' => 'African Leopard', 'scientific_name' => 'Panthera pardus pardus',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Carnivore', 'lifespan' => '12-17 years',
                'conservation_status' => 'Vulnerable',
                'description' => 'The leopard is the most elusive and adaptable of Africa\'s big cats. A supreme ambush hunter, it can haul prey twice its own weight up into trees to protect it from lions and hyenas. Leopards are the only big cat that regularly stores food in trees and are remarkably strong swimmers, sometimes hunting fish and crabs.',
                'image' => '/images/animals/leopard-1.jpg',
                'gallery' => json_encode(['/images/animals/leopard-1.jpg', '/images/animals/leopard-2.jpg']),
                'fun_facts' => json_encode(['Leopards can drag prey twice their weight up into trees.', 'They are the only big cats that regularly cache food in trees.', 'Black leopards ("black panthers") are actually spotted — it\'s just hard to see against their dark fur.']),
                'weight' => '90 kg', 'height' => '0.8 m', 'speed' => '58 km/h',
            ],
            [
                'name' => 'Vervet Monkey', 'species' => 'Vervet Monkey', 'scientific_name' => 'Chlorocebus pygerythrus',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Omnivore', 'lifespan' => '12-24 years',
                'conservation_status' => 'Least Concern',
                'description' => 'Vervet monkeys are highly social primates that have developed one of the most sophisticated alarm call systems in the animal kingdom. They use distinct calls for eagles (others look up), snakes (others look down) and leopards (others run into trees) — showing they have a basic form of language with referential meaning.',
                'image' => '/images/animals/vervet-monkey-1.jpg',
                'gallery' => json_encode(['/images/animals/vervet-monkey-1.jpg', '/images/animals/vervet-monkey-2.jpg']),
                'fun_facts' => json_encode(['Vervet monkeys use different alarm calls for eagles, snakes, and leopards.', 'They have been observed "bartering" — exchanging social grooming for food.', 'Infant vervets are born with pink faces that darken with age.']),
                'weight' => '5 kg', 'height' => '0.5 m', 'speed' => '35 km/h',
            ],
            [
                'name' => 'Aardvark', 'species' => 'Aardvark', 'scientific_name' => 'Orycteropus afer',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Insectivore', 'lifespan' => '18-23 years',
                'conservation_status' => 'Least Concern',
                'description' => 'The aardvark is one of Africa\'s most peculiar animals — a solitary, nocturnal mammal that has no close living relatives. Using its powerful claws and 30 cm sticky tongue, it can eat up to 50,000 ants and termites in a single night. Aardvarks are ecosystem engineers — their abandoned burrows become homes for dozens of other species.',
                'image' => '/images/animals/aardvark-1.jpg',
                'gallery' => json_encode(['/images/animals/aardvark-1.jpg', '/images/animals/aardvark-2.jpg']),
                'fun_facts' => json_encode(['Aardvarks can eat 50,000 ants in a single night.', 'Their abandoned burrows become homes for warthogs, hyenas, and monitor lizards.', '"Aardvark" means "earth pig" in Afrikaans.']),
                'weight' => '65 kg', 'height' => '0.6 m', 'speed' => '40 km/h',
            ],
            [
                'name' => "Thomson's Gazelle", 'species' => "Thomson's Gazelle", 'scientific_name' => 'Eudorcas thomsonii',
                'category' => 'Mammal', 'habitat_id' => 5, 'diet' => 'Herbivore', 'lifespan' => '10-15 years',
                'conservation_status' => 'Least Concern',
                'description' => 'Thomson\'s gazelle is one of the most abundant antelopes in Africa and a cornerstone prey species of the Serengeti ecosystem. Famous for "stotting" — bouncing high on stiff legs when a predator is spotted — this behaviour is thought to signal fitness to the predator, saying "I\'m too healthy to bother chasing."',
                'image' => '/images/animals/gazelle-1.jpg',
                'gallery' => json_encode(['/images/animals/gazelle-1.jpg', '/images/animals/gazelle-2.jpg']),
                'fun_facts' => json_encode(['"Stotting" — bouncing on stiff legs — signals fitness to predators.', 'Cheetahs are their primary predator, and gazelles can outmanoeuvre them at top speed.', 'They can go days without water, getting moisture from grass.']),
                'weight' => '30 kg', 'height' => '0.65 m', 'speed' => '80 km/h',
            ],
            [
                'name' => 'Secretary Bird', 'species' => 'Secretary Bird', 'scientific_name' => 'Sagittarius serpentarius',
                'category' => 'Bird', 'habitat_id' => 5, 'diet' => 'Carnivore', 'lifespan' => '10-15 years',
                'conservation_status' => 'Endangered',
                'description' => 'The secretary bird is one of Africa\'s most extraordinary raptors — a large bird of prey that hunts entirely on foot, striding across the savannah on its long legs. It kills prey including venomous snakes by stamping on them with tremendous force — delivering a kick five times its own body weight in just 15 milliseconds.',
                'image' => '/images/animals/secretary-bird-1.jpg',
                'gallery' => json_encode(['/images/animals/secretary-bird-1.jpg', '/images/animals/secretary-bird-2.jpg']),
                'fun_facts' => json_encode(['Secretary birds kill snakes by stomping with 5x their body weight.', 'Their kick is faster than the human eye can follow — 15 milliseconds.', 'They walk up to 30 km per day hunting on foot.']),
                'weight' => '3.5 kg', 'height' => '1.35 m', 'speed' => '40 km/h',
            ],
        ];

        foreach ($animals as $animal) {
            Animal::create($animal);
        }
    }
}
